# Generated by Django 3.2.5 on 2021-08-03 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart5_app', '0002_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='pric',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='stock',
            field=models.IntegerField(),
        ),
    ]
