# Generated by Django 3.2.5 on 2021-08-03 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart5_app', '0003_auto_20210803_1203'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categ',
            options={'ordering': ('name',), 'verbose_name': 'categories'},
        ),
    ]
