# Generated by Django 3.2.5 on 2021-08-04 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart5_app', '0005_products_available'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='pric',
            new_name='price',
        ),
    ]
