# Generated by Django 3.2.5 on 2021-08-04 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart5_app', '0006_rename_pric_products_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='img',
            field=models.ImageField(upload_to='image'),
        ),
    ]
